### ISSUE TITLE
Error in Javascript Detector

### ISSUE THREAD

**Issue by nicholaswkc34** [AutomatedOwl/chromedriver-js-errors-collector#4]
Dear Support, 

I tried to using this javascript error detector but Im encounter an issue where exception is throw and I don't know what is the root cause? 
May I know how to solve this?

Error Message: 
```
org.openqa.selenium.json.JsonException: Unable to determine type from: H. Last 1 characters read: H
Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:19:58.91Z'
System info: host: 'DESKTOP-P6PRQOR', ip: '192.168.56.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '9.0.4'
Driver info: driver.version: RemoteWebDriver
	at org.openqa.selenium.json.JsonInput.peek(JsonInput.java:121)
	at org.openqa.selenium.json.JsonTypeCoercer.lambda$null$6(JsonTypeCoercer.java:137)
	at org.openqa.selenium.json.JsonTypeCoercer.coerce(JsonTypeCoercer.java:123)
	at org.openqa.selenium.json.Json.toType(Json.java:60)
	at org.openqa.selenium.json.Json.toType(Json.java:50)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:87)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:548)
	at org.openqa.selenium.remote.RemoteExecuteMethod.execute(RemoteExecuteMethod.java:35)
	at org.openqa.selenium.remote.RemoteLogs.getRemoteEntries(RemoteLogs.java:81)
	at org.openqa.selenium.remote.RemoteLogs.get(RemoteLogs.java:77)
	at com.github.automatedowl.tools.JSErrorsCollectorListener.getLogEntriesForTest(JSErrorsCollectorListener.java:98)
	at com.github.automatedowl.tools.JSErrorsCollectorListener.afterInvocation(JSErrorsCollectorListener.java:44)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1380)
... Removed 29 stack frames
```

Source Code: 
```
@BeforeMethod
void setDriverForListener(Method method) {
        // Set your test name to point its ChromeDriver session in HashMap.
        JSErrorsDriverHolder.setDriverForTest(method.getName(), (WebDriver) myChromeDriver.getDriver());
        JSErrorsDriverHolder.setDriverForTest(method.getName(), (WebDriver) myFirefoxDriver.getDriver());
}

 @Test(groups= {"Login"}, description="Chrome - Login"/*, dataProvider = "loginCredentials",*/, retryAnalyzer = RetryAnalyzer.class)
    @JSErrorsCollectorTestNG(assertJSErrors = true)
    public void test() {
        myChromeDriver.getDriver().navigate().to("https://www.facebook.com");
        myFirefoxDriver.getDriver().navigate().to("https://www.google.com.my");
    }
```

Please help me on this.  A billion thanks for your help.

**Comment by AutomatedOwl** [comment]
Hi, @peterwkc85 can you try just with chromedriver instead of both chromedriver and firedox?
